Ecal prefire fix
artus-analysis/Excalibur pull request #90
Opened 2022-03-08 11:05 UTC by cverstege

2022-03-08 11:25 UTC, HerrHorizontal requested changes
Some minor comments inline.

2022-03-08 11:25 UTC, HerrHorizontal commented on Compile/src/Producers/PrefiringWeightProducer.cc
> +    auto& invalidJets = product.m_correctedInvalidJets["L1L2L3Res"];
Für den Fall, dass die `L1L2L3Res` Pipeline nicht konfiguriert ist, scheitert das natürlich. Vielleicht sollte man das abfangen.

2022-03-08 11:25 UTC, HerrHorizontal commented on Compile/src/Producers/PrefiringWeightProducer.cc
>      product.m_optionalWeights["prefiringWeight"] =  1./nonPrefiringProba[0];
Kann man das nominelle Weight nicht zu dem Event-Weight hinzufügen?

2022-03-08 12:23 UTC, cverstege commented on Compile/src/Producers/PrefiringWeightProducer.cc
>      product.m_optionalWeights["prefiringWeight"] =  1./nonPrefiringProba[0];
Natürlich

2022-03-08 12:31 UTC, cverstege commented on Compile/src/Producers/PrefiringWeightProducer.cc
> +    auto& invalidJets = product.m_correctedInvalidJets["L1L2L3Res"];
Log Warning weiter unten bei 0 Jets

2022-03-15 13:30 UTC, cverstege commented
Fixed a bug when calculating the weights. Also moved back to optionalWeights, as those weights are only applied at reco level, not on gen level.
Should be ready now. Please re-review @HerrHorizontal @RHofsaess

2022-03-15 13:31 UTC, cverstege commented
I'll squash and merge one approved, so it's only one commit on the master branch in the end.

2022-03-15 16:02 UTC, HerrHorizontal approved these changes
Luckily, you have spotted the bug. Looks good now! :+1:

2022-03-16 13:16 UTC, RHofsaess commented on Compile/interface/ZJetProduct.h
> +            return static_cast<KLV*>(m_invalidJets[index]);
is this really correct?
eventually this is implicitely casted to usigned long when returning?

2022-03-16 13:23 UTC, RHofsaess approved these changes
Looks good :+1:

2022-03-17 15:36 UTC, merged