Veto jet eta phi
artus-analysis/Excalibur pull request #93
Opened 2022-05-19 13:05 UTC by RHofsaess

With this PR the possibility is added to veto events where one of the first N leading jets (above a threshold) is cleaned by the JetEtaPhiCleaner.
It is activated with `CutVetoCleanedEvents=true`
The threshold can be chosen with `CutVetoJetsAbove=<VALUE>`
The number of jets to be checked: `CutVetoNJets=<VALUE>` (default is 1 -- veto the event when the leading jet is cleaned)

2022-05-19 13:28 UTC, HerrHorizontal requested changes
Looks fine! Just some typos.

2022-05-19 13:28 UTC, HerrHorizontal commented on Compile/interface/ZJetSettings.h
> +    IMPL_SETTING_DEFAULT(int, CutVetoNJets, 1)  // default: only check leading jet; to check all jets, use 999
This can in principle be bigger than 999, since it is an `int`. Maybe remove this comment.

2022-05-19 13:28 UTC, HerrHorizontal commented on Compile/interface/Producers/JetCleaner.h
> + * For this, the allready implemented functionality is reused ( I know it is
"allready"->"already"

2022-05-19 13:28 UTC, HerrHorizontal commented on Compile/interface/Producers/JetCleaner.h
> + * loop since the immidiate removal would prevent this.
"immidiate"->"immediate"

2022-05-19 13:28 UTC, HerrHorizontal commented on Compile/interface/Producers/JetCleaner.h
> + * In the end, the remove is always gets a false since this should only happen
"gets a"->"returns"

2022-05-19 14:16 UTC, HerrHorizontal approved these changes
Looks fine now.

2022-05-23 11:59 UTC, cverstege approved these changes

2022-05-23 12:05 UTC, merged